In [1]:
import scipy.io
from scipy.io import savemat
from scipy.sparse import csr_matrix
import numpy as np

## Inst File Example

In [2]:
#Load inst file
my_mat = scipy.io.loadmat('2011_003276.mat')
my_mat

{'GTinst': array([[ (array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), array([[ <400x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 154 stored elements in Compressed Sparse Column format>]], dtype=object), array([[3]], dtype=uint8))]], 
       dtype=[('Segmentation', 'O'), ('Boundaries', 'O'), ('Categories', 'O')]),
 '__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Jan  8 04:43:39 2012',
 '__version__': '1.0'}

In [3]:
val = my_mat['GTinst'][0,0]
my_segment = val['Segmentation']
my_segment

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [4]:
my_loaded_boundaries =  val['Boundaries']
my_loaded_boundaries

array([[ <400x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 154 stored elements in Compressed Sparse Column format>]], dtype=object)

In [5]:
#Expand boundaries sparse matrix
my_boundaries = val['Boundaries'][0,0].toarray()
my_boundaries

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [6]:
my_categories = val['Categories']
my_categories

array([[3]], dtype=uint8)

## Cls File Example

In [8]:
my_mat2 = scipy.io.loadmat('2008_000227.mat')
my_mat2

//anaconda/envs/gdalenv/lib/python3.5/site-packages/scipy/sparse/compressed.py:294: SparseEfficiencyWarning: Comparing sparse matrices using >= and <= is inefficient, using <, >, or !=, instead.
  "using <, >, or !=, instead.", SparseEfficiencyWarning)


{'GTcls': array([[ (array([[ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 0 stored elements in Compressed Sparse Column format>],
        [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 0 stored elements in Compressed Sparse Column format>],
        [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 0 stored elements in Compressed Sparse Column format>],
        [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 0 stored elements in Compressed Sparse Column format>],
        [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 0 stored elements in Compressed Sparse Column format>],
        [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 0 stored elements in Compressed Sparse Column format>],
        [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 0 stored elements in Compressed Sparse Column format>],
        [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
 	with 943 stored el

In [12]:
val2 = my_mat2['GTcls'][0,0]
my_segment2 = val2['Segmentation']
my_segment2

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ..., 
       [11, 11, 11, ...,  0,  0,  0],
       [11, 11, 11, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=uint8)

In [13]:
my_loaded_boundaries2 =  val2['Boundaries']
my_loaded_boundaries2

//anaconda/envs/gdalenv/lib/python3.5/site-packages/scipy/sparse/compressed.py:294: SparseEfficiencyWarning: Comparing sparse matrices using >= and <= is inefficient, using <, >, or !=, instead.
  "using <, >, or !=, instead.", SparseEfficiencyWarning)


array([[ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 0 stored elements in Compressed Sparse Column format>],
       [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 0 stored elements in Compressed Sparse Column format>],
       [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 0 stored elements in Compressed Sparse Column format>],
       [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 0 stored elements in Compressed Sparse Column format>],
       [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 0 stored elements in Compressed Sparse Column format>],
       [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 0 stored elements in Compressed Sparse Column format>],
       [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 0 stored elements in Compressed Sparse Column format>],
       [ <375x500 sparse matrix of type '<class 'numpy.uint8'>'
	with 943 stored elements in Compressed Sparse Column 

In [14]:
my_categories2 = val2['CategoriesPresent']
my_categories2

array([[ 8],
       [ 9],
       [11]], dtype=uint8)